### ISSUE TITLE
Android 6 UnsatisfiedLinkError when user opened game

### ISSUE THREAD

**Issue by smks** [openfl/openfl#1064]
java.lang.UnsatisfiedLinkError: dlopen failed: library "C:\Development\Android NDK/platforms/android-9/arch-arm/usr/lib/libc.so" not found
    at java.lang.Runtime.loadLibrary(Runtime.java:372)
    at java.lang.System.loadLibrary(System.java:1076)
    at org.haxe.HXCPP.run(HXCPP.java:18)
    at org.haxe.lime.GameActivity.onCreate(GameActivity.java:120)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by danielmar** [comment]
Are you using SDK 23? This also happens to me with 23, and is fixed if I use 22 instead.

**Comment by jgranick** [comment]
This is resolved with using newer Android NDK versions :smile:
