### ISSUE TITLE
Gradient Return Error on html5

### ISSUE THREAD

**Issue by PXshadow** [openfl/openfl#1852]
When creating a new shape with a gradient Fill html5 build crashes, works fine however on Android, Neko and Windows.
```
Uncaught DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('rgba(255, 255, 255, undefined)') could not be parsed as a color.
    at Function.openfl__$internal_renderer_canvas_CanvasGraphics.createGradientPattern (http://127.0.0.1:8000/ThinQbator.js:51763:16)
    at Function.openfl__$internal_renderer_canvas_CanvasGraphics.playCommands (http://127.0.0.1:8000/ThinQbator.js:53464:122)
    at Function.openfl__$internal_renderer_canvas_CanvasGraphics.endFill (http://127.0.0.1:8000/ThinQbator.js:51829:51)
    at Function.openfl__$internal_renderer_canvas_CanvasGraphics.render (http://127.0.0.1:8000/ThinQbator.js:56289:54)
    at core_Shadow.__renderCanvas (http://127.0.0.1:8000/ThinQbator.js:2238:58)
    at openfl_display_BitmapData.__draw (http://127.0.0.1:8000/ThinQbator.js:67726:11)
    at core_Shadow.__updateCacheBitmap (http://127.0.0.1:8000/ThinQbator.js:2611:28)
    at core_Shadow.__renderGL (http://127.0.0.1:8000/ThinQbator.js:2333:8)
    at Profile.__renderGL (http://127.0.0.1:8000/ThinQbator.js:3654:12)
    at core_App.__renderGL (http://127.0.0.1:8000/ThinQbator.js:3654:12)
```

**Comment by jgranick** [comment]
How is your `alphas` array being constructed?

**Comment by PXshadow** [comment]
It's just an array with [1,1]

**Comment by jgranick** [comment]
It looks like the loop runs for the number of values in the `colors` array. Is that also two values long?

**Comment by PXshadow** [comment]
There are more than 2 values for the colors 😞 
```graphics.beginGradientFill(openfl.display.GradientType.LINEAR, [0, 9211020, 16777215], [1, 1], [0, 40, 255],mat);```

**Comment by jgranick** [comment]
Okay, thanks, I'll do some more testing

**Comment by jgranick** [comment]
Okay, looks like A.) Flash ignores the call if the array sizes don't match and B.) supports null alpha or ratio arrays, so I've just committed an update that should help with both :smile:
